WINDOW = "camera"

# STATES
WAIT_FOR_BUTTON = "WAIT_FOR_BUTTON"

DETECT_PIPES_IN_IMAGE = "DETECT_PIPES_IN_IMAGE"
LOOK_LEFT = "LOOK_LEFT"
DETECT_PIPES_IN_IMAGE_LEFT = "DETECT_PIPES_IN_IMAGE_LEFT"
LOOK_RIGHT = "LOOK_RIGHT"
DETECT_PIPES_IN_IMAGE_RIGHT = "DETECT_PIPES_IN_IMAGE_RIGHT"
LOOK_BACK_TO_CENTER = "LOOK_BACK_TO_CENTER"

MEASURE_DISTANCE_TO_GATE = "MEASURE_DISTANCE_TO_GATE"
INCREASE_LOOKOUT_ANGLE = "INCREASE_LOOKOUT_ANGLE"

ROTATE_TOWARD_GATE = "ROTATE_TOWARD_GATE"
DRIVE_TOWARD_GATE = "DRIVE_TOWARD_GATE"
ROTATE_TO_FACE_GATE = "ROTATE_TO_FACE_GATE"
DRIVE_THROUGH_GATE = "DRIVE_THROUGH_GATE"
DETECT_NEXT_GATE_COLOR = "DETECT_NEXT_GATE_COLOR"

# GATE COLORS
RED = "RED"
GREEN = "GREEN"
BLUE = "BLUE"

# BUMPER CONSTANTS
BUMPER_NAMES = ["LEFT", "CENTER", "RIGHT"]
BUMPER_STATES = ["RELEASED", "PRESSED"]

# BUTTON CONSTANTS
BUTTON_STATES = ["RELEASED", "PRESSED"]
