WINDOW = "camera"

# STATES
LOOKING_FOR_GATE = "LOOKING_FOR_GATE"
MEASURE_DISTANCE_TO_GATE = "MEASURE_DISTANCE_TO_GATE"
ROTATE_LEFT_TOWARD_GATE = "ROTATE_LEFT_TOWARD_GATE"
ROTATE_RIGHT_TOWARD_GATE = "ROTATE_RIGHT_TOWARD_GATE"
MOVE_TO_GATE = "MOVE_TO_GATE"
FACE_GATE = "FACE_GATE"
GO_THROUGH_GATE = "GO_THROUGH_GATE"
ROTATE_RIGHT = "ROTATE_RIGHT"
ROTATE_LEFT = "ROTATE_LEFT"
FINISH = "FINISH"

# GATE COLORS
RED = "RED"
GREEN = "GREEN"
BLUE = "BLUE"

# BUMPER CONSTANTS
BUMPER_NAMES = ["LEFT", "CENTER", "RIGHT"]
BUMPER_STATES = ["RELEASED", "PRESSED"]